import { expect, test } from "@playwright/test";
import { randomUUID } from "node:crypto";

const origin = "http://127.0.0.1:3000";
const backend = "http://127.0.0.1:8000";

test("live dashboard: readings, filters, saving, refresh, failures and responsive layout", async ({ page, context }) => {
  test.setTimeout(150_000);
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  const credentials = { email: `dashboard-${randomUUID()}@example.com`, password: randomUUID() };
  const request = context.request;
  const headers = { Origin: origin };
  const farms: string[] = [];
  const register = await request.post(`${origin}/api/auth/register`, { headers, data: { ...credentials, full_name: "Dashboard Verification" } });
  expect(register.status()).toBe(201);
  expect((await request.post(`${origin}/api/auth/login`, { headers, data: credentials })).status()).toBe(200);
  try {
    await page.goto(`${origin}/dashboard`);
    await expect(page.getByText("No farms are registered to this account.")).toBeVisible();
    const populatedResponse = await request.post(`${origin}/api/farms`, { headers, data: { name: "South Field", location: "Nagercoil, Tamil Nadu", latitude: "8.17899", longitude: "77.43227", area_hectares: "2.5", soil_type: "loamy" } });
    expect(populatedResponse.status()).toBe(201);
    const populated = await populatedResponse.json();
    farms.push(populated.id);
    const emptyResponse = await request.post(`${origin}/api/farms`, { headers, data: { name: "North Field", location: "Nagercoil" } });
    expect(emptyResponse.status()).toBe(201);
    const empty = await emptyResponse.json();
    farms.push(empty.id);
    const capabilities = ["soil_moisture", "temperature", "humidity", "ph", "nitrogen", "phosphorus", "potassium", "rainfall"];
    const deviceResponse = await request.post(`${origin}/api/farms/${populated.id}/devices`, { headers, data: { name: "Simulated field station", serial_number: `TEST-${randomUUID()}`, capabilities } });
    expect(deviceResponse.status()).toBe(201);
    const device = await deviceResponse.json();
    const ingest = async (readings: { metric: string; value: string; recorded_at?: string }[]) => {
      const response = await request.post(`${backend}/farms/${populated.id}/devices/${device.id}/readings`, { headers: { "X-Device-Key": device.device_key }, data: { source: "simulated", readings } });
      expect(response.status()).toBe(201);
    };
    const values = ["58", "27", "71", "6.4", "45", "22", "31"];
    await ingest(capabilities.slice(0, 7).map((metric, index) => ({ metric, value: values[index] })));
    await ingest([{ metric: "rainfall", value: "0" }]);
    for (const days of [2, 10]) {
      await ingest([{ metric: "soil_moisture", value: String(58 - days), recorded_at: new Date(Date.now() - days * 86_400_000).toISOString() }]);
    }
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.reload();
    const moisture = page.getByRole("article", { name: "Soil moisture", exact: true });
    await expect(moisture).toContainText("58 %");
    await expect(moisture).toContainText("Simulated");
    await expect(page.getByRole("region", { name: "Data readiness" })).toContainText("8 of 8 metrics recorded.");
    await expect(page.getByRole("region", { name: "Farm devices" })).toContainText("Connected");
    await expect(page.getByRole("img", { name: "Soil moisture chart, 2 readings" })).toBeVisible();
    await page.getByRole("tab", { name: "24h", exact: true }).click();
    await expect(page.getByRole("img", { name: "Soil moisture chart, 1 readings" })).toBeVisible();
    await page.getByRole("tab", { name: "30 days", exact: true }).click();
    await expect(page.getByRole("img", { name: "Soil moisture chart, 3 readings" })).toBeVisible();
    const downloadPromise = page.waitForEvent("download");
    await page.getByRole("button", { name: "Download filtered readings" }).click();
    const download = await downloadPromise;
    const stream = await download.createReadStream();
    let csv = "";
    for await (const chunk of stream!) csv += chunk.toString();
    expect(csv).toContain('"source"');
    expect(csv.match(/"simulated"/g)).toHaveLength(3);
    await page.getByLabel("Chart metric").selectOption("rainfall");
    await expect(page.getByRole("img", { name: "Rainfall chart, 1 readings" })).toBeVisible();
    await page.getByRole("button", { name: "Refresh dashboard" }).click();
    await expect(page.getByLabel("Chart metric")).toHaveValue("rainfall");
    await expect(page.getByRole("tab", { name: "30 days", exact: true })).toHaveAttribute("data-state", "active");
    await expect(page.getByRole("img", { name: "Rainfall chart, 1 readings" })).toBeVisible();
    await page.getByLabel("Auto-refresh 60s").check();
    await page.clock.install();
    await page.getByRole("button", { name: "Add soil test" }).click();
    const dialog = page.getByRole("dialog", { name: "Add soil test" });
    await dialog.getByLabel("Soil pH", { exact: true }).fill("0");
    const refreshed = page.waitForResponse((response) => response.url().endsWith(`/farms/${populated.id}/readings/latest`));
    await page.clock.fastForward(60_001);
    await refreshed;
    await expect(dialog.getByLabel("Soil pH", { exact: true })).toHaveValue("0");
    await page.clock.resume();
    await page.route(`**/api/farms/${populated.id}/readings`, async (route) => {
      if (route.request().method() === "POST") await route.fulfill({ status: 503, json: { detail: "Test write unavailable" } });
      else await route.continue();
    });
    await dialog.getByRole("button", { name: "Save readings" }).click();
    await expect(dialog.getByRole("alert")).toHaveText("Test write unavailable");
    await expect(dialog.getByLabel("Soil pH", { exact: true })).toHaveValue("0");
    await page.unroute(`**/api/farms/${populated.id}/readings`);
    await dialog.getByRole("button", { name: "Save readings" }).click();
    await expect(dialog).toBeHidden();
    const ph = page.getByRole("article", { name: "Soil pH", exact: true });
    await expect(ph).toContainText("Manual test");
    await expect(ph.locator("p").filter({ hasText: /^0$/ })).toBeVisible();
    const latest = await request.get(`${origin}/api/farms/${populated.id}/readings/latest`);
    expect((await latest.json()).find((reading: { metric: string }) => reading.metric === "ph")).toMatchObject({ source: "manual", value: "0.0000" });
    await page.getByLabel("Auto-refresh 60s").uncheck();
    await page.getByLabel("Select farm", { exact: true }).selectOption(empty.id);
    await expect(page.getByRole("region", { name: "Data readiness" })).toContainText("0 of 8 metrics recorded.");
    await expect(moisture).toContainText("No reading");
    await expect(page.getByText("Add farm coordinates to see its forecast.")).toBeVisible();
    await page.getByLabel("Select farm", { exact: true }).selectOption(populated.id);
    await page.getByLabel("Select farm", { exact: true }).selectOption(empty.id);
    await expect(moisture).toContainText("No reading");
    await expect(moisture).not.toContainText("58 %");
    await page.getByLabel("Select farm", { exact: true }).selectOption(populated.id);
    await expect(moisture).toContainText("58 %");
    await expect(page.getByRole("region", { name: "Farm weather" }).getByRole("status")).toHaveCount(0);
    console.log("Weather panel:", await page.getByRole("region", { name: "Farm weather" }).innerText());
    await page.screenshot({ path: "/tmp/agrisense-dashboard-desktop.png", fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: "/tmp/agrisense-dashboard-mobile.png", fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
    await page.getByRole("button", { name: "Add soil test" }).click();
    await expect(dialog).toBeVisible();
    const bounds = await dialog.boundingBox();
    expect(bounds!.x).toBeGreaterThanOrEqual(0);
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(390);
    await expect(dialog).toHaveCSS("opacity", "1");
    await page.screenshot({ path: "/tmp/agrisense-dashboard-soil-mobile.png" });
    await dialog.getByRole("button", { name: "Cancel" }).click();
    await page.route("**/api/weather/farms/*", (route) => route.fulfill({ status: 503, json: { detail: "Test weather unavailable" } }));
    await page.getByRole("button", { name: "Refresh dashboard" }).click();
    await expect(page.getByText("Test weather unavailable", { exact: true })).toBeVisible();
    await expect(moisture).toContainText("58 %");
    await page.route(`**/api/farms/${populated.id}/readings/latest`, (route) => route.fulfill({ status: 503, json: { detail: "Test readings unavailable" } }));
    await page.getByRole("button", { name: "Refresh dashboard" }).click();
    await expect(page.getByText("Readings: Test readings unavailable", { exact: true })).toBeVisible();
    await expect(moisture).toContainText("Unavailable");
    await expect(moisture).not.toContainText("58 %");
    await expect(page.getByRole("region", { name: "Farm devices" })).toContainText("Connected");
    await page.unroute(`**/api/farms/${populated.id}/readings/latest`);
    await page.route(`**/api/farms/${populated.id}/readings/latest`, (route) => route.fulfill({ status: 401, json: { detail: "Session expired" } }));
    await context.clearCookies();
    await page.getByRole("button", { name: "Refresh dashboard" }).click();
    await expect(page).toHaveURL(`${origin}/login`);
    expect(errors).toEqual([]);
  } finally {
    await request.post(`${origin}/api/auth/login`, { headers, data: credentials });
    for (const farm of farms) expect((await request.delete(`${origin}/api/farms/${farm}`, { headers })).status()).toBe(204);
    await request.post(`${origin}/api/auth/logout`, { headers });
  }
});